theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.png'
    footer: '/assets/images/logo.png'
  image_sizes:
    sections:
      home:
        hero:
          mobile: 800
          tablet: 1400
          desktop: 1920
      pages:
        hero:
          mobile: 800
          tablet: 1400
          desktop: 1920
  home:
    head:
      title: site
  posts:
    default_image: false
    date_format: ":date_long"
    index:
      layout: list # grid | list
      options:
        author: false
        categories: true
        date: true
        image: true
        reading_time: false
        summary: true
        subtitle: true
      truncate_description: 200 # Set to 0 to disable truncate
    single:
      options:
        authors: false
        published_at: true
        reading_time: false
        signature: false
        updated_at: false
    share_links: # Optional
      enabled: true
      email: true
      facebook: false
      linkedin: true
      mastodon: false
      telegram: false
      twitter: false
      whatsapp: false